# -*- coding: utf-8 -*-
"""clean_salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjEbLy8KW27S_YPdah49g_WmkAi-VV4B
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('df.csv')

df

df.info()  #5892 non-null:it mean that there are 5892 data points in a dataset that are not empty or missing

int(3.6)

df['Rating'][0]

df['Rating'][5891]

int(df['Rating'][5891])

df['Rating'].apply(int)

df['Salary Estimate'].apply(lambda x: x.replace('(Glassdoor est.)' ,'').replace('$','') #You can use the replace function to clean any additional information, and you can also apply the function to all 5891 data using the apply function. #salary_estimate #salary-calculator